/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ActionGroup: typeof import('./src/components/ActionGroup.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    Logo: typeof import('./src/components/Logo.vue')['default']
    MenuDrawer: typeof import('./src/components/MenuDrawer.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SelectTreeMenu: typeof import('./src/components/SelectTreeMenu.vue')['default']
    UApp: typeof import('./node_modules/.pnpm/@nuxt+ui@4.1.0_@babel+parser@7.28.5_async-validator@4.2.5_axios@1.12.2_embla-carousel@8_bdde5e508bdaf4f799fb7ed9d6a6eac3/node_modules/@nuxt/ui/dist/runtime/components/App.vue')['default']
    UAuthForm: typeof import('./node_modules/.pnpm/@nuxt+ui@4.1.0_@babel+parser@7.28.5_embla-carousel@8.6.0_typescript@5.9.3_vite@7.1.12_@_0e3a8cc5c208cf45f3fbafedb935054c/node_modules/@nuxt/ui/dist/runtime/components/AuthForm.vue')['default']
    UAvatar: typeof import('./node_modules/.pnpm/@nuxt+ui@4.1.0_@babel+parser@7.28.5_async-validator@4.2.5_axios@1.12.2_embla-carousel@8_bdde5e508bdaf4f799fb7ed9d6a6eac3/node_modules/@nuxt/ui/dist/runtime/components/Avatar.vue')['default']
    UBadge: typeof import('./node_modules/.pnpm/@nuxt+ui@4.1.0_@babel+parser@7.28.5_async-validator@4.2.5_axios@1.12.2_embla-carousel@8_bdde5e508bdaf4f799fb7ed9d6a6eac3/node_modules/@nuxt/ui/dist/runtime/components/Badge.vue')['default']
    UBreadcrumb: typeof import('./node_modules/.pnpm/@nuxt+ui@4.1.0_@babel+parser@7.28.5_async-validator@4.2.5_axios@1.12.2_embla-carousel@8_bdde5e508bdaf4f799fb7ed9d6a6eac3/node_modules/@nuxt/ui/dist/runtime/components/Breadcrumb.vue')['default']
    UButton: typeof import('./node_modules/.pnpm/@nuxt+ui@4.1.0_@babel+parser@7.28.5_async-validator@4.2.5_axios@1.12.2_embla-carousel@8_bdde5e508bdaf4f799fb7ed9d6a6eac3/node_modules/@nuxt/ui/dist/runtime/components/Button.vue')['default']
    UCard: typeof import('./node_modules/.pnpm/@nuxt+ui@4.1.0_@babel+parser@7.28.5_async-validator@4.2.5_axios@1.12.2_embla-carousel@8_bdde5e508bdaf4f799fb7ed9d6a6eac3/node_modules/@nuxt/ui/dist/runtime/components/Card.vue')['default']
    UCheckbox: typeof import('./node_modules/.pnpm/@nuxt+ui@4.1.0_@babel+parser@7.28.5_async-validator@4.2.5_axios@1.12.2_embla-carousel@8_bdde5e508bdaf4f799fb7ed9d6a6eac3/node_modules/@nuxt/ui/dist/runtime/components/Checkbox.vue')['default']
    UCheckboxGroup: typeof import('./node_modules/.pnpm/@nuxt+ui@4.1.0_@babel+parser@7.28.5_axios@1.12.2_embla-carousel@8.6.0_typescript@5.9.3__3bd03ac2b33cfe68ba17739e1f706186/node_modules/@nuxt/ui/dist/runtime/components/CheckboxGroup.vue')['default']
    UDashboardGroup: typeof import('./node_modules/.pnpm/@nuxt+ui@4.1.0_@babel+parser@7.28.5_async-validator@4.2.5_axios@1.12.2_embla-carousel@8_bdde5e508bdaf4f799fb7ed9d6a6eac3/node_modules/@nuxt/ui/dist/runtime/components/DashboardGroup.vue')['default']
    UDashboardNavbar: typeof import('./node_modules/.pnpm/@nuxt+ui@4.1.0_@babel+parser@7.28.5_async-validator@4.2.5_axios@1.12.2_embla-carousel@8_bdde5e508bdaf4f799fb7ed9d6a6eac3/node_modules/@nuxt/ui/dist/runtime/components/DashboardNavbar.vue')['default']
    UDashboardPanel: typeof import('./node_modules/.pnpm/@nuxt+ui@4.1.0_@babel+parser@7.28.5_axios@1.12.2_embla-carousel@8.6.0_typescript@5.9.3__4e869f4ad43fd779e53e0787ee8fa704/node_modules/@nuxt/ui/dist/runtime/components/DashboardPanel.vue')['default']
    UDashboardSidebar: typeof import('./node_modules/.pnpm/@nuxt+ui@4.1.0_@babel+parser@7.28.5_async-validator@4.2.5_axios@1.12.2_embla-carousel@8_bdde5e508bdaf4f799fb7ed9d6a6eac3/node_modules/@nuxt/ui/dist/runtime/components/DashboardSidebar.vue')['default']
    UDashboardSidebarCollapse: typeof import('./node_modules/.pnpm/@nuxt+ui@4.1.0_@babel+parser@7.28.5_async-validator@4.2.5_axios@1.12.2_embla-carousel@8_bdde5e508bdaf4f799fb7ed9d6a6eac3/node_modules/@nuxt/ui/dist/runtime/components/DashboardSidebarCollapse.vue')['default']
    UDashboardToolbar: typeof import('./node_modules/.pnpm/@nuxt+ui@4.1.0_@babel+parser@7.28.5_axios@1.12.2_embla-carousel@8.6.0_typescript@5.9.3__4e869f4ad43fd779e53e0787ee8fa704/node_modules/@nuxt/ui/dist/runtime/components/DashboardToolbar.vue')['default']
    UDropdownMenu: typeof import('./node_modules/.pnpm/@nuxt+ui@4.1.0_@babel+parser@7.28.5_async-validator@4.2.5_axios@1.12.2_embla-carousel@8_bdde5e508bdaf4f799fb7ed9d6a6eac3/node_modules/@nuxt/ui/dist/runtime/components/DropdownMenu.vue')['default']
    UFieldGroup: typeof import('./node_modules/.pnpm/@nuxt+ui@4.1.0_@babel+parser@7.28.5_async-validator@4.2.5_axios@1.12.2_embla-carousel@8_bdde5e508bdaf4f799fb7ed9d6a6eac3/node_modules/@nuxt/ui/dist/runtime/components/FieldGroup.vue')['default']
    UForm: typeof import('./node_modules/.pnpm/@nuxt+ui@4.1.0_@babel+parser@7.28.5_async-validator@4.2.5_axios@1.12.2_embla-carousel@8_bdde5e508bdaf4f799fb7ed9d6a6eac3/node_modules/@nuxt/ui/dist/runtime/components/Form.vue')['default']
    UFormField: typeof import('./node_modules/.pnpm/@nuxt+ui@4.1.0_@babel+parser@7.28.5_async-validator@4.2.5_axios@1.12.2_embla-carousel@8_bdde5e508bdaf4f799fb7ed9d6a6eac3/node_modules/@nuxt/ui/dist/runtime/components/FormField.vue')['default']
    UIcon: typeof import('./node_modules/.pnpm/@nuxt+ui@4.1.0_@babel+parser@7.28.5_async-validator@4.2.5_axios@1.12.2_embla-carousel@8_bdde5e508bdaf4f799fb7ed9d6a6eac3/node_modules/@nuxt/ui/dist/runtime/vue/components/Icon.vue')['default']
    UInput: typeof import('./node_modules/.pnpm/@nuxt+ui@4.1.0_@babel+parser@7.28.5_async-validator@4.2.5_axios@1.12.2_embla-carousel@8_bdde5e508bdaf4f799fb7ed9d6a6eac3/node_modules/@nuxt/ui/dist/runtime/components/Input.vue')['default']
    UInputMenu: typeof import('./node_modules/.pnpm/@nuxt+ui@4.1.0_@babel+parser@7.28.5_axios@1.12.2_embla-carousel@8.6.0_typescript@5.9.3__3bd03ac2b33cfe68ba17739e1f706186/node_modules/@nuxt/ui/dist/runtime/components/InputMenu.vue')['default']
    UModal: typeof import('./node_modules/.pnpm/@nuxt+ui@4.1.0_@babel+parser@7.28.5_async-validator@4.2.5_axios@1.12.2_embla-carousel@8_bdde5e508bdaf4f799fb7ed9d6a6eac3/node_modules/@nuxt/ui/dist/runtime/components/Modal.vue')['default']
    UNavigationMenu: typeof import('./node_modules/.pnpm/@nuxt+ui@4.1.0_@babel+parser@7.28.5_async-validator@4.2.5_axios@1.12.2_embla-carousel@8_bdde5e508bdaf4f799fb7ed9d6a6eac3/node_modules/@nuxt/ui/dist/runtime/components/NavigationMenu.vue')['default']
    UPageCard: typeof import('./node_modules/.pnpm/@nuxt+ui@4.1.0_@babel+parser@7.28.5_async-validator@4.2.5_axios@1.12.2_embla-carousel@8_bdde5e508bdaf4f799fb7ed9d6a6eac3/node_modules/@nuxt/ui/dist/runtime/components/PageCard.vue')['default']
    UPagination: typeof import('./node_modules/.pnpm/@nuxt+ui@4.1.0_@babel+parser@7.28.5_async-validator@4.2.5_axios@1.12.2_embla-carousel@8_bdde5e508bdaf4f799fb7ed9d6a6eac3/node_modules/@nuxt/ui/dist/runtime/components/Pagination.vue')['default']
    UPinInput: typeof import('./node_modules/.pnpm/@nuxt+ui@4.1.0_@babel+parser@7.28.5_embla-carousel@8.6.0_typescript@5.9.3_vite@7.1.12_@_0e3a8cc5c208cf45f3fbafedb935054c/node_modules/@nuxt/ui/dist/runtime/components/PinInput.vue')['default']
    UPopover: typeof import('./node_modules/.pnpm/@nuxt+ui@4.1.0_@babel+parser@7.28.5_async-validator@4.2.5_axios@1.12.2_embla-carousel@8_bdde5e508bdaf4f799fb7ed9d6a6eac3/node_modules/@nuxt/ui/dist/runtime/components/Popover.vue')['default']
    URadioGroup: typeof import('./node_modules/.pnpm/@nuxt+ui@4.1.0_@babel+parser@7.28.5_axios@1.12.2_embla-carousel@8.6.0_typescript@5.9.3__3bd03ac2b33cfe68ba17739e1f706186/node_modules/@nuxt/ui/dist/runtime/components/RadioGroup.vue')['default']
    USlideover: typeof import('./node_modules/.pnpm/@nuxt+ui@4.1.0_@babel+parser@7.28.5_async-validator@4.2.5_axios@1.12.2_embla-carousel@8_bdde5e508bdaf4f799fb7ed9d6a6eac3/node_modules/@nuxt/ui/dist/runtime/components/Slideover.vue')['default']
    USwitch: typeof import('./node_modules/.pnpm/@nuxt+ui@4.1.0_@babel+parser@7.28.5_async-validator@4.2.5_axios@1.12.2_embla-carousel@8_bdde5e508bdaf4f799fb7ed9d6a6eac3/node_modules/@nuxt/ui/dist/runtime/components/Switch.vue')['default']
    UTable: typeof import('./node_modules/.pnpm/@nuxt+ui@4.1.0_@babel+parser@7.28.5_async-validator@4.2.5_axios@1.12.2_embla-carousel@8_bdde5e508bdaf4f799fb7ed9d6a6eac3/node_modules/@nuxt/ui/dist/runtime/components/Table.vue')['default']
    UTabs: typeof import('./node_modules/.pnpm/@nuxt+ui@4.1.0_@babel+parser@7.28.5_async-validator@4.2.5_axios@1.12.2_embla-carousel@8_bdde5e508bdaf4f799fb7ed9d6a6eac3/node_modules/@nuxt/ui/dist/runtime/components/Tabs.vue')['default']
    UTextarea: typeof import('./node_modules/.pnpm/@nuxt+ui@4.1.0_@babel+parser@7.28.5_axios@1.12.2_embla-carousel@8.6.0_typescript@5.9.3__3bd03ac2b33cfe68ba17739e1f706186/node_modules/@nuxt/ui/dist/runtime/components/Textarea.vue')['default']
    UTooltip: typeof import('./node_modules/.pnpm/@nuxt+ui@4.1.0_@babel+parser@7.28.5_async-validator@4.2.5_axios@1.12.2_embla-carousel@8_bdde5e508bdaf4f799fb7ed9d6a6eac3/node_modules/@nuxt/ui/dist/runtime/components/Tooltip.vue')['default']
    UTree: typeof import('./node_modules/.pnpm/@nuxt+ui@4.1.0_@babel+parser@7.28.5_async-validator@4.2.5_axios@1.12.2_embla-carousel@8_bdde5e508bdaf4f799fb7ed9d6a6eac3/node_modules/@nuxt/ui/dist/runtime/components/Tree.vue')['default']
    WarningModal: typeof import('./src/components/WarningModal.vue')['default']
  }
}
